apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
data:
  application.yml: |
    spring:
      pulsar:
        client: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
          clientConfig:
            serviceUrl: "pulsar://host.docker.internal:6650"
        consumer:
          enabled: true
          consumerConfig: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-producer
            topicNames: "anotha" 
            subscriptionName: "sub"
        admin: 
          adminConfig: # Accepts the same key-value pair configurations as pulsar client: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
            serviceUrl: "http://host.docker.internal:8080"
        
          