apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  limits: 
    readBatchSize: 1
  vertices:
    - name: in
      scale:
        min: 1
      volumes: # Shared between containers that are part of the same pod, useful for sharing configurations
        - name: pulsar-config-volume
          configMap:
            name: pulsar-config 
            items:
              - key: application.yml
                path: application.yml
      source:
        udsource: 
          container:
            image: apache-pulsar-java:v0.3.0
            args: [ "--spring.config.location=file:/conf/application.yml" ] # Use external configuration file 
            imagePullPolicy: Never
            volumeMounts:
              - name: pulsar-config-volume
                mountPath: /conf
    - name: p1
      scale:
        min: 1
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: p1
    - from: p1
      to: out