apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-source-pipeline
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        udsource: 
          container: 
            image: quay.io/numaio/numaflow-rs/simple-source:stable
       
    - name: cat
      scale:
        min: 1
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out