apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar-config
data:
  application.yml: |
    spring:
      pulsar:
      
        client: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
          clientConfig:
            serviceUrl: "pulsar://host.docker.internal:6650"
        producer:
          enabled: false
        consumer: 
          enabled: true
          consumerConfig: 
            topicNames: "marchten"
            subscriptionName: "sub"





