apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar-config-map
data:
  application.yml: |
    spring:
      pulsar:
        client: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
          clientConfig:
            serviceUrl: "pulsar://host.docker.internal:6650"
        producer:
          enabled: true
          producerConfig: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-producer
            topicName: "schema-topic" 
            sendTimeoutMs: 2000