# API Key example
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar-config
data:
  application.yml: |
    spring:
      pulsar:
        client: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
          clientConfig:
            serviceUrl: "insert pulsar+ssl:// ...." # brokerServiceUrl
            authPluginClassName: org.apache.pulsar.client.impl.auth.AuthenticationToken
            authParams: "insert key" # add API key here
        consumer:  # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-consumer
          enabled: true
          consumerConfig: 
            topicName: "persistent://public/default/test-topic"
            subscriptionName: "test-subscription"
        admin: 
          adminConfig: # Accepts the same key-value pair configurations as pulsar client: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
            serviceUrl: "insert pulsar+ssl:// ...." # brokerServiceUrl
            authPluginClassName: org.apache.pulsar.client.impl.auth.AuthenticationToken
            authParams: "insert key" # add API key here