# API Key example
apiVersion: v1
kind: ConfigMap
metadata:
  name: byte-arr-producer-config
data:
  application.yml: |
    spring:
      pulsar:
        client: # see here for all configurations: https://pulsar.apache.org/reference/#/4.0.x/client/client-configuration-client
          clientConfig:
            serviceUrl: "insert pulsar+ssl:// ...." # brokerServiceUrl here 
            authPluginClassName: org.apache.pulsar.client.impl.auth.AuthenticationToken
            authParams: "insert key" # add API key here
        producer:
          enabled: true
          producerConfig: 
            topicName: "persistent://public/default/test-topic"
